# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UP_UX.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 729)
        MainWindow.setMinimumSize(QtCore.QSize(500, 729))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 2000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/teamwork.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("\n"
"background-color: rgb(220,220,220);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.About_Us = QtWidgets.QTabWidget(self.centralwidget)
        self.About_Us.setEnabled(True)
        self.About_Us.setMinimumSize(QtCore.QSize(450, 450))
        self.About_Us.setMaximumSize(QtCore.QSize(2000, 2000))
        self.About_Us.setAutoFillBackground(False)
        self.About_Us.setIconSize(QtCore.QSize(16, 16))
        self.About_Us.setUsesScrollButtons(True)
        self.About_Us.setTabBarAutoHide(True)
        self.About_Us.setObjectName("About_Us")
        self.Take_Attendance = QtWidgets.QWidget()
        self.Take_Attendance.setMinimumSize(QtCore.QSize(450, 450))
        self.Take_Attendance.setMaximumSize(QtCore.QSize(2000, 2000))
        self.Take_Attendance.setObjectName("Take_Attendance")
        self.LCDtotalFaceCountTakeAttendance = QtWidgets.QLCDNumber(self.Take_Attendance)
        self.LCDtotalFaceCountTakeAttendance.setGeometry(QtCore.QRect(780, 430, 121, 51))
        self.LCDtotalFaceCountTakeAttendance.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.LCDtotalFaceCountTakeAttendance.setFrameShape(QtWidgets.QFrame.Box)
        self.LCDtotalFaceCountTakeAttendance.setObjectName("LCDtotalFaceCountTakeAttendance")
        self.labelFaceCountTakeAttendance = QtWidgets.QLabel(self.Take_Attendance)
        self.labelFaceCountTakeAttendance.setGeometry(QtCore.QRect(780, 400, 111, 21))
        self.labelFaceCountTakeAttendance.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.labelFaceCountTakeAttendance.setTextFormat(QtCore.Qt.RichText)
        self.labelFaceCountTakeAttendance.setScaledContents(True)
        self.labelFaceCountTakeAttendance.setIndent(2)
        self.labelFaceCountTakeAttendance.setObjectName("labelFaceCountTakeAttendance")
        self.rawImage = QtWidgets.QLabel(self.Take_Attendance)
        self.rawImage.setGeometry(QtCore.QRect(30, 10, 721, 551))
        self.rawImage.setText("")
        self.rawImage.setPixmap(QtGui.QPixmap(".\\picture.png"))
        self.rawImage.setAlignment(QtCore.Qt.AlignCenter)
        self.rawImage.setObjectName("rawImage")
        self.startProcessingButton = QtWidgets.QPushButton(self.Take_Attendance)
        self.startProcessingButton.setGeometry(QtCore.QRect(770, 200, 141, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startProcessingButton.setFont(font)
        self.startProcessingButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 0, rgb(116, 116, 116)qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255)));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/camera/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startProcessingButton.setIcon(icon1)
        self.startProcessingButton.setIconSize(QtCore.QSize(20, 20))
        self.startProcessingButton.setObjectName("startProcessingButton")
        self.progressBarProcessingTakeAttendance = QtWidgets.QProgressBar(self.Take_Attendance)
        self.progressBarProcessingTakeAttendance.setGeometry(QtCore.QRect(460, 610, 501, 23))
        self.progressBarProcessingTakeAttendance.setProperty("value", 24)
        self.progressBarProcessingTakeAttendance.setObjectName("progressBarProcessingTakeAttendance")
        self.PROCESSING_STATUS = QtWidgets.QLabel(self.Take_Attendance)
        self.PROCESSING_STATUS.setGeometry(QtCore.QRect(300, 610, 151, 20))
        self.PROCESSING_STATUS.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.PROCESSING_STATUS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PROCESSING_STATUS.setObjectName("PROCESSING_STATUS")
        self.imagePath = QtWidgets.QLineEdit(self.Take_Attendance)
        self.imagePath.setGeometry(QtCore.QRect(760, 70, 211, 20))
        self.imagePath.setAutoFillBackground(False)
        self.imagePath.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagePath.setAlignment(QtCore.Qt.AlignCenter)
        self.imagePath.setObjectName("imagePath")
        self.loadImageButtonTakeAttendance = QtWidgets.QPushButton(self.Take_Attendance)
        self.loadImageButtonTakeAttendance.setGeometry(QtCore.QRect(870, 100, 101, 21))
        self.loadImageButtonTakeAttendance.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 0, 0);")
        self.loadImageButtonTakeAttendance.setIcon(icon1)
        self.loadImageButtonTakeAttendance.setIconSize(QtCore.QSize(20, 20))
        self.loadImageButtonTakeAttendance.setObjectName("loadImageButtonTakeAttendance")
        self.LCDFaceCountTakeAttendance = QtWidgets.QLCDNumber(self.Take_Attendance)
        self.LCDFaceCountTakeAttendance.setGeometry(QtCore.QRect(780, 530, 121, 51))
        self.LCDFaceCountTakeAttendance.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.LCDFaceCountTakeAttendance.setFrameShape(QtWidgets.QFrame.Box)
        self.LCDFaceCountTakeAttendance.setObjectName("LCDFaceCountTakeAttendance")
        self.labelFaceCount2TakeAttendance = QtWidgets.QLabel(self.Take_Attendance)
        self.labelFaceCount2TakeAttendance.setGeometry(QtCore.QRect(780, 500, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelFaceCount2TakeAttendance.setFont(font)
        self.labelFaceCount2TakeAttendance.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.labelFaceCount2TakeAttendance.setTextFormat(QtCore.Qt.RichText)
        self.labelFaceCount2TakeAttendance.setScaledContents(True)
        self.labelFaceCount2TakeAttendance.setIndent(2)
        self.labelFaceCount2TakeAttendance.setObjectName("labelFaceCount2TakeAttendance")
        self.label_26 = QtWidgets.QLabel(self.Take_Attendance)
        self.label_26.setGeometry(QtCore.QRect(10, 610, 211, 51))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).jpg"))
        self.label_26.setObjectName("label_26")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/camera/photograph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About_Us.addTab(self.Take_Attendance, icon2, "")
        self.Register_Faces = QtWidgets.QWidget()
        self.Register_Faces.setObjectName("Register_Faces")
        self.imageRecordingRegister_Faces = QtWidgets.QLabel(self.Register_Faces)
        self.imageRecordingRegister_Faces.setGeometry(QtCore.QRect(20, 10, 500, 500))
        self.imageRecordingRegister_Faces.setStyleSheet("image: url(:/icons/facial-recognition.png);")
        self.imageRecordingRegister_Faces.setFrameShape(QtWidgets.QFrame.Box)
        self.imageRecordingRegister_Faces.setText("")
        self.imageRecordingRegister_Faces.setScaledContents(True)
        self.imageRecordingRegister_Faces.setAlignment(QtCore.Qt.AlignCenter)
        self.imageRecordingRegister_Faces.setObjectName("imageRecordingRegister_Faces")
        self.progressBar = QtWidgets.QProgressBar(self.Register_Faces)
        self.progressBar.setGeometry(QtCore.QRect(50, 520, 471, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 62)
        self.progressBar.setObjectName("progressBar")
        self.registerPushButtonRegister_Faces = QtWidgets.QPushButton(self.Register_Faces)
        self.registerPushButtonRegister_Faces.setGeometry(QtCore.QRect(670, 510, 285, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.registerPushButtonRegister_Faces.setFont(font)
        self.registerPushButtonRegister_Faces.setAutoFillBackground(False)
        self.registerPushButtonRegister_Faces.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.registerPushButtonRegister_Faces.setObjectName("registerPushButtonRegister_Faces")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Register_Faces)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 10, 421, 451))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.nAMELabel = QtWidgets.QLabel(self.groupBox_3)
        self.nAMELabel.setGeometry(QtCore.QRect(0, 70, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nAMELabel.setFont(font)
        self.nAMELabel.setObjectName("nAMELabel")
        self.rOLL_NUMBERLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.rOLL_NUMBERLineEdit.setGeometry(QtCore.QRect(0, 160, 280, 20))
        self.rOLL_NUMBERLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rOLL_NUMBERLineEdit.setObjectName("rOLL_NUMBERLineEdit")
        self.nAMELineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.nAMELineEdit.setGeometry(QtCore.QRect(0, 90, 280, 20))
        self.nAMELineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nAMELineEdit.setObjectName("nAMELineEdit")
        self.sEMESTERComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sEMESTERComboBox.setGeometry(QtCore.QRect(0, 280, 280, 18))
        self.sEMESTERComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sEMESTERComboBox.setObjectName("sEMESTERComboBox")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sCHOOL_CODEComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sCHOOL_CODEComboBox.setGeometry(QtCore.QRect(0, 350, 280, 18))
        self.sCHOOL_CODEComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sCHOOL_CODEComboBox.setObjectName("sCHOOL_CODEComboBox")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sECTIONComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sECTIONComboBox.setGeometry(QtCore.QRect(0, 220, 280, 18))
        self.sECTIONComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sECTIONComboBox.setObjectName("sECTIONComboBox")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.rOLL_NUMBERLabel = QtWidgets.QLabel(self.groupBox_3)
        self.rOLL_NUMBERLabel.setGeometry(QtCore.QRect(0, 140, 66, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rOLL_NUMBERLabel.setFont(font)
        self.rOLL_NUMBERLabel.setObjectName("rOLL_NUMBERLabel")
        self.sCHOOL_CODELabel = QtWidgets.QLabel(self.groupBox_3)
        self.sCHOOL_CODELabel.setGeometry(QtCore.QRect(0, 320, 80, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sCHOOL_CODELabel.setFont(font)
        self.sCHOOL_CODELabel.setObjectName("sCHOOL_CODELabel")
        self.sEMESTERLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sEMESTERLabel.setGeometry(QtCore.QRect(0, 260, 57, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sEMESTERLabel.setFont(font)
        self.sEMESTERLabel.setObjectName("sEMESTERLabel")
        self.sECTIONLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sECTIONLabel.setGeometry(QtCore.QRect(0, 200, 47, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sECTIONLabel.setFont(font)
        self.sECTIONLabel.setObjectName("sECTIONLabel")
        self.label_30 = QtWidgets.QLabel(self.Register_Faces)
        self.label_30.setGeometry(QtCore.QRect(0, 610, 211, 51))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).jpg"))
        self.label_30.setObjectName("label_30")
        self.About_Us.addTab(self.Register_Faces, icon, "")
        self.RESULTS = QtWidgets.QWidget()
        self.RESULTS.setObjectName("RESULTS")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.RESULTS)
        self.tableWidget_2.setGeometry(QtCore.QRect(30, 60, 341, 511))
        self.tableWidget_2.setStyleSheet("gridline-color: rgb(0, 255, 0);\n"
"selection-background-color: rgb(0, 216, 104);")
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.label_13 = QtWidgets.QLabel(self.RESULTS)
        self.label_13.setGeometry(QtCore.QRect(150, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.groupBox_4 = QtWidgets.QGroupBox(self.RESULTS)
        self.groupBox_4.setGeometry(QtCore.QRect(400, 100, 331, 401))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(40, 50, 251, 321))
        self.tableWidget_3.setStyleSheet("gridline-color: rgb(0, 255, 0);\n"
"selection-background-color: rgb(0, 216, 104);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.label_14 = QtWidgets.QLabel(self.RESULTS)
        self.label_14.setGeometry(QtCore.QRect(770, 140, 91, 16))
        self.label_14.setObjectName("label_14")
        self.lcdCounter_10 = QtWidgets.QLCDNumber(self.RESULTS)
        self.lcdCounter_10.setGeometry(QtCore.QRect(770, 170, 121, 61))
        self.lcdCounter_10.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounter_10.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounter_10.setObjectName("lcdCounter_10")
        self.label_15 = QtWidgets.QLabel(self.RESULTS)
        self.label_15.setGeometry(QtCore.QRect(900, 140, 91, 16))
        self.label_15.setObjectName("label_15")
        self.lcdCounter_11 = QtWidgets.QLCDNumber(self.RESULTS)
        self.lcdCounter_11.setGeometry(QtCore.QRect(900, 170, 121, 61))
        self.lcdCounter_11.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounter_11.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounter_11.setObjectName("lcdCounter_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.RESULTS)
        self.pushButton_5.setGeometry(QtCore.QRect(800, 260, 201, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.RESULTS)
        self.pushButton_6.setGeometry(QtCore.QRect(850, 20, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("alternate-background-color: rgb(255, 255, 0);\n"
"selection-color: rgb(0, 255, 255);\n"
"selection-background-color: rgb(255, 170, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_27 = QtWidgets.QLabel(self.RESULTS)
        self.label_27.setGeometry(QtCore.QRect(0, 610, 211, 51))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).jpg"))
        self.label_27.setObjectName("label_27")
        self.groupBox_4.raise_()
        self.tableWidget_2.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.lcdCounter_10.raise_()
        self.label_15.raise_()
        self.lcdCounter_11.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.label_27.raise_()
        self.About_Us.addTab(self.RESULTS, "")
        self.M_Attendance = QtWidgets.QWidget()
        self.M_Attendance.setObjectName("M_Attendance")
        self.tableWidget = QtWidgets.QTableWidget(self.M_Attendance)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 331, 641))
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.groupBox = QtWidgets.QGroupBox(self.M_Attendance)
        self.groupBox.setGeometry(QtCore.QRect(460, 20, 541, 321))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color: rgb(123, 123, 185);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 130, 191, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(10, 260, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 60, 191, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 190, 191, 22))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(310, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(310, 190, 191, 22))
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(310, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(310, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(310, 60, 191, 22))
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(310, 130, 191, 22))
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 290, 161, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.M_Attendance)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 370, 521, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcdCounter_8 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdCounter_8.setGeometry(QtCore.QRect(350, 90, 121, 61))
        self.lcdCounter_8.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounter_8.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounter_8.setObjectName("lcdCounter_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(350, 60, 91, 16))
        self.label_4.setObjectName("label_4")
        self.lcdCounter_7 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdCounter_7.setGeometry(QtCore.QRect(200, 90, 121, 61))
        self.lcdCounter_7.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounter_7.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounter_7.setObjectName("lcdCounter_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 91, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 90, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(90, 130, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 210, 311, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.About_Us.addTab(self.M_Attendance, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 70, 1011, 421))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.iMAGE_PATHLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.iMAGE_PATHLineEdit.setGeometry(QtCore.QRect(190, 90, 565, 20))
        self.iMAGE_PATHLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.iMAGE_PATHLineEdit.setObjectName("iMAGE_PATHLineEdit")
        self.dATASET_SAVE_PATHLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.dATASET_SAVE_PATHLineEdit.setGeometry(QtCore.QRect(190, 20, 565, 20))
        self.dATASET_SAVE_PATHLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dATASET_SAVE_PATHLineEdit.setObjectName("dATASET_SAVE_PATHLineEdit")
        self.eXCEL_SHEET_PATHLabel = QtWidgets.QLabel(self.groupBox_5)
        self.eXCEL_SHEET_PATHLabel.setGeometry(QtCore.QRect(190, 140, 99, 20))
        self.eXCEL_SHEET_PATHLabel.setObjectName("eXCEL_SHEET_PATHLabel")
        self.saveButton = QtWidgets.QPushButton(self.groupBox_5)
        self.saveButton.setGeometry(QtCore.QRect(180, 240, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setAutoFillBackground(False)
        self.saveButton.setStyleSheet("color: red;\n"
"background-color: rgba(170, 255, 255, 150);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.saveButton.setObjectName("saveButton")
        self.eXCEL_SHEET_PATHLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.eXCEL_SHEET_PATHLineEdit.setGeometry(QtCore.QRect(190, 160, 565, 20))
        self.eXCEL_SHEET_PATHLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.eXCEL_SHEET_PATHLineEdit.setObjectName("eXCEL_SHEET_PATHLineEdit")
        self.iMAGE_PATHLabel = QtWidgets.QLabel(self.groupBox_5)
        self.iMAGE_PATHLabel.setGeometry(QtCore.QRect(190, 70, 64, 20))
        self.iMAGE_PATHLabel.setObjectName("iMAGE_PATHLabel")
        self.dATASET_SAVE_PATHLabel = QtWidgets.QLabel(self.groupBox_5)
        self.dATASET_SAVE_PATHLabel.setGeometry(QtCore.QRect(190, 0, 108, 20))
        self.dATASET_SAVE_PATHLabel.setObjectName("dATASET_SAVE_PATHLabel")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(110, 630, 47, 13))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(0, 610, 211, 51))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).jpg"))
        self.label_29.setObjectName("label_29")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About_Us.addTab(self.tab, icon3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_7)
        self.textBrowser.setGeometry(QtCore.QRect(-10, 30, 1031, 651))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(10, 260, 981, 51))
        self.label_17.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setGeometry(QtCore.QRect(50, 330, 191, 191))
        self.label_18.setStyleSheet("image: url(:/photos/kundan.jpeg);")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).png"))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setGeometry(QtCore.QRect(300, 330, 211, 191))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/photos/castro.png);")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (3).png"))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_7)
        self.label_20.setGeometry(QtCore.QRect(550, 320, 181, 211))
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/photos/azra.jpeg);")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (2).png"))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(760, 300, 221, 241))
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/photos/prudhvi.png);")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(".\\../../Pictures/Webp.net-resizeimage (4).png"))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(16, 542, 221, 81))
        self.label_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setGeometry(QtCore.QRect(300, 540, 221, 81))
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(540, 540, 221, 81))
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(780, 540, 221, 81))
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_16 = QtWidgets.QLabel(self.tab_7)
        self.label_16.setGeometry(QtCore.QRect(400, 120, 201, 101))
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.textBrowser.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_16.raise_()
        self.About_Us.addTab(self.tab_7, "")
        self.gridLayout.addWidget(self.About_Us, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionoen = QtWidgets.QAction(MainWindow)
        self.actionoen.setObjectName("actionoen")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionuct = QtWidgets.QAction(MainWindow)
        self.actionuct.setObjectName("actionuct")
        self.actioncoopy = QtWidgets.QAction(MainWindow)
        self.actioncoopy.setObjectName("actioncoopy")
        self.actionTAKE_ATTENDANCE = QtWidgets.QAction(MainWindow)
        self.actionTAKE_ATTENDANCE.setIcon(icon1)
        self.actionTAKE_ATTENDANCE.setObjectName("actionTAKE_ATTENDANCE")
        self.actionREGISTER = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/camera/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionREGISTER.setIcon(icon4)
        self.actionREGISTER.setObjectName("actionREGISTER")
        self.actionSETTINGS = QtWidgets.QAction(MainWindow)
        self.actionSETTINGS.setIcon(icon3)
        self.actionSETTINGS.setObjectName("actionSETTINGS")

        self.retranslateUi(MainWindow)
        self.About_Us.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UNIVERSITY_PROJECT-1"))
        self.labelFaceCountTakeAttendance.setText(_translate("MainWindow", "Total Face Count"))
        self.startProcessingButton.setText(_translate("MainWindow", "Start Processing"))
        self.startProcessingButton.setShortcut(_translate("MainWindow", "F5"))
        self.PROCESSING_STATUS.setText(_translate("MainWindow", "PROCESSING_STATUS :"))
        self.imagePath.setText(_translate("MainWindow", "imagePathTakeAttendance"))
        self.loadImageButtonTakeAttendance.setText(_translate("MainWindow", "Load Image"))
        self.loadImageButtonTakeAttendance.setShortcut(_translate("MainWindow", "F5"))
        self.labelFaceCount2TakeAttendance.setText(_translate("MainWindow", "identified Face Count"))
        self.About_Us.setTabText(self.About_Us.indexOf(self.Take_Attendance), _translate("MainWindow", "Take_Attendance"))
        self.registerPushButtonRegister_Faces.setText(_translate("MainWindow", "REGISTER"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fill the details Below"))
        self.nAMELabel.setText(_translate("MainWindow", "NAME"))
        self.sEMESTERComboBox.setItemText(0, _translate("MainWindow", "SEM_1"))
        self.sEMESTERComboBox.setItemText(1, _translate("MainWindow", "SEM_2"))
        self.sEMESTERComboBox.setItemText(2, _translate("MainWindow", "SEM_3"))
        self.sEMESTERComboBox.setItemText(3, _translate("MainWindow", "SEM_4"))
        self.sEMESTERComboBox.setItemText(4, _translate("MainWindow", "SEM_5"))
        self.sEMESTERComboBox.setItemText(5, _translate("MainWindow", "SEM_6"))
        self.sEMESTERComboBox.setItemText(6, _translate("MainWindow", "SEM_7"))
        self.sEMESTERComboBox.setItemText(7, _translate("MainWindow", "SEM_8"))
        self.sEMESTERComboBox.setItemText(8, _translate("MainWindow", "SEM_9"))
        self.sEMESTERComboBox.setItemText(9, _translate("MainWindow", "SEM_10"))
        self.sCHOOL_CODEComboBox.setItemText(0, _translate("MainWindow", "SOE"))
        self.sCHOOL_CODEComboBox.setItemText(1, _translate("MainWindow", "SOM"))
        self.sCHOOL_CODEComboBox.setItemText(2, _translate("MainWindow", "SOC"))
        self.sCHOOL_CODEComboBox.setItemText(3, _translate("MainWindow", "SOL"))
        self.sCHOOL_CODEComboBox.setItemText(4, _translate("MainWindow", "M.TECH"))
        self.sCHOOL_CODEComboBox.setItemText(5, _translate("MainWindow", "Phd"))
        self.sECTIONComboBox.setItemText(0, _translate("MainWindow", "5cse5"))
        self.sECTIONComboBox.setItemText(1, _translate("MainWindow", "5cse6"))
        self.sECTIONComboBox.setItemText(2, _translate("MainWindow", "5cse7"))
        self.sECTIONComboBox.setItemText(3, _translate("MainWindow", "5cse8"))
        self.sECTIONComboBox.setItemText(4, _translate("MainWindow", "5cse9"))
        self.sECTIONComboBox.setItemText(5, _translate("MainWindow", "5cse10"))
        self.rOLL_NUMBERLabel.setText(_translate("MainWindow", "ID_NUMBER"))
        self.sCHOOL_CODELabel.setText(_translate("MainWindow", "SCHOOL"))
        self.sEMESTERLabel.setText(_translate("MainWindow", "SEMESTER"))
        self.sECTIONLabel.setText(_translate("MainWindow", "SECTION"))
        self.About_Us.setTabText(self.About_Us.indexOf(self.Register_Faces), _translate("MainWindow", "Register_Faces"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID.No"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.label_13.setText(_translate("MainWindow", "Result"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Absents"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_3.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_3.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_3.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_3.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_3.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_3.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_3.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_3.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_3.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID.No"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Total Presents"))
        self.label_15.setText(_translate("MainWindow", "Total Absents"))
        self.pushButton_5.setText(_translate("MainWindow", "CONFIRM And Update in ERP"))
        self.pushButton_6.setText(_translate("MainWindow", "EDIT"))
        self.About_Us.setTabText(self.About_Us.indexOf(self.RESULTS), _translate("MainWindow", "RESULTS"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID.No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Attendance(X/A)"))
        self.groupBox.setTitle(_translate("MainWindow", "Choose Class Details"))
        self.label_5.setText(_translate("MainWindow", "Class."))
        self.label_6.setText(_translate("MainWindow", "Faculty Name."))
        self.label_7.setText(_translate("MainWindow", "Course Code."))
        self.label_8.setText(_translate("MainWindow", "Period No."))
        self.comboBox.setItemText(0, _translate("MainWindow", "5CSE1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "5CSE2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "5CSE3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "5CSE4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5CSE5"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "CSE123"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "CSE001"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "CSE258"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "CSE985"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "CSE456"))
        self.label_9.setText(_translate("MainWindow", "Semester."))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "8"))
        self.label_10.setText(_translate("MainWindow", "School."))
        self.label_11.setText(_translate("MainWindow", "Branch."))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "SOE"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "SOM"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "SOL"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "SOC"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "M.TECH"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "P.hD"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "CSE"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "EEE"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "ECE"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "MEC"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "PET"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "BBA"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "BA"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result"))
        self.label_4.setText(_translate("MainWindow", "Total Absents"))
        self.label_3.setText(_translate("MainWindow", "Total Presents"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        self.pushButton.setText(_translate("MainWindow", "Save "))
        self.pushButton_4.setText(_translate("MainWindow", "Confirm And Update in ERP"))
        self.About_Us.setTabText(self.About_Us.indexOf(self.M_Attendance), _translate("MainWindow", "M_Attendance"))
        self.eXCEL_SHEET_PATHLabel.setText(_translate("MainWindow", "EXCEL_SHEET_PATH"))
        self.saveButton.setText(_translate("MainWindow", "SAVE BUTTON"))
        self.iMAGE_PATHLabel.setText(_translate("MainWindow", "IMAGE_PATH"))
        self.dATASET_SAVE_PATHLabel.setText(_translate("MainWindow", "DATASET_SAVE_PATH"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.About_Us.setTabText(self.About_Us.indexOf(self.tab), _translate("MainWindow", "SETTINGS"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\"> This facial Recognition Attendence System is a part of University Project held in Pesidency University Computer Science Branch for       the year 2019-20.</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Brains Behind The Project</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">KUNDAN MUNDA NS </span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0331</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">CASTRO K JOSEPH </span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0145</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">AZRA BANU </span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0105</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">PRUDHVI RAJ</span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0138</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Our Guide</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">MS.ILLA CHANDRAKAR</span></p></body></html>"))
        self.About_Us.setTabText(self.About_Us.indexOf(self.tab_7), _translate("MainWindow", "About Us"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionoen.setText(_translate("MainWindow", "open"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionuct.setText(_translate("MainWindow", "uct"))
        self.actioncoopy.setText(_translate("MainWindow", "coopy"))
        self.actionTAKE_ATTENDANCE.setText(_translate("MainWindow", "TAKE_ATTENDANCE"))
        self.actionTAKE_ATTENDANCE.setToolTip(_translate("MainWindow", "takes_attendance"))
        self.actionREGISTER.setText(_translate("MainWindow", "REGISTER"))
        self.actionREGISTER.setToolTip(_translate("MainWindow", "maps to register screen"))
        self.actionSETTINGS.setText(_translate("MainWindow", "SETTINGS"))
        self.actionSETTINGS.setToolTip(_translate("MainWindow", "configuring the locations"))
import iconsPackage_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
