# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UP_UX.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 729)
        MainWindow.setMinimumSize(QtCore.QSize(500, 729))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 2000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("teamwork.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("\n"
"background-color: rgb(220,220,220);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setEnabled(True)
        self.Tabs.setMinimumSize(QtCore.QSize(450, 450))
        self.Tabs.setMaximumSize(QtCore.QSize(2000, 2000))
        self.Tabs.setAutoFillBackground(False)
        self.Tabs.setIconSize(QtCore.QSize(16, 16))
        self.Tabs.setUsesScrollButtons(True)
        self.Tabs.setTabBarAutoHide(True)
        self.Tabs.setObjectName("Tabs")
        self.Take_Attendance = QtWidgets.QWidget()
        self.Take_Attendance.setMinimumSize(QtCore.QSize(450, 450))
        self.Take_Attendance.setMaximumSize(QtCore.QSize(2000, 2000))
        self.Take_Attendance.setObjectName("Take_Attendance")
        self.LCDtotalFaceCountTakeAttendance = QtWidgets.QLCDNumber(self.Take_Attendance)
        self.LCDtotalFaceCountTakeAttendance.setGeometry(QtCore.QRect(780, 430, 121, 51))
        self.LCDtotalFaceCountTakeAttendance.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.LCDtotalFaceCountTakeAttendance.setFrameShape(QtWidgets.QFrame.Box)
        self.LCDtotalFaceCountTakeAttendance.setObjectName("LCDtotalFaceCountTakeAttendance")
        self.labelFaceCountTakeAttendance = QtWidgets.QLabel(self.Take_Attendance)
        self.labelFaceCountTakeAttendance.setGeometry(QtCore.QRect(780, 400, 111, 21))
        self.labelFaceCountTakeAttendance.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.labelFaceCountTakeAttendance.setTextFormat(QtCore.Qt.RichText)
        self.labelFaceCountTakeAttendance.setScaledContents(True)
        self.labelFaceCountTakeAttendance.setIndent(2)
        self.labelFaceCountTakeAttendance.setObjectName("labelFaceCountTakeAttendance")
        self.rawImage = QtWidgets.QLabel(self.Take_Attendance)
        self.rawImage.setGeometry(QtCore.QRect(30, 10, 721, 551))
        self.rawImage.setText("")
        self.rawImage.setStyleSheet("image: url(:teamwork.png);")
        #self.rawImage.setPixmap(QtGui.QPixmap("C:\\Users\\kundan\\Desktop\\uiFiles\\CastroUI\\uiFiles (1)\\uiFiles\\images\\iconsimages/icons/picture.png"))
        #self.rawImage.setPixmap(QtGui.QPixmap(".\\picture.png"))
        self.rawImage.setAlignment(QtCore.Qt.AlignCenter)
        self.rawImage.setObjectName("rawImage")
        self.startProcessingButton = QtWidgets.QPushButton(self.Take_Attendance)
        self.startProcessingButton.setGeometry(QtCore.QRect(770, 200, 141, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startProcessingButton.setFont(font)
        self.startProcessingButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 0, rgb(116, 116, 116)qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255)));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startProcessingButton.setIcon(icon1)
        self.startProcessingButton.setIconSize(QtCore.QSize(20, 20))
        self.startProcessingButton.setObjectName("startProcessingButton")
        self.progressBarProcessingTakeAttendance = QtWidgets.QProgressBar(self.Take_Attendance)
        self.progressBarProcessingTakeAttendance.setGeometry(QtCore.QRect(460, 610, 501, 23))
        self.progressBarProcessingTakeAttendance.setProperty("value", 24)
        self.progressBarProcessingTakeAttendance.setObjectName("progressBarProcessingTakeAttendance")
        self.PROCESSING_STATUS = QtWidgets.QLabel(self.Take_Attendance)
        self.PROCESSING_STATUS.setGeometry(QtCore.QRect(300, 610, 151, 20))
        self.PROCESSING_STATUS.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.PROCESSING_STATUS.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PROCESSING_STATUS.setObjectName("PROCESSING_STATUS")
        self.imagePath = QtWidgets.QLineEdit(self.Take_Attendance)
        self.imagePath.setGeometry(QtCore.QRect(760, 70, 211, 20))
        self.imagePath.setAutoFillBackground(False)
        self.imagePath.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagePath.setAlignment(QtCore.Qt.AlignCenter)
        self.imagePath.setObjectName("imagePath")
        self.loadImageButtonTakeAttendance = QtWidgets.QPushButton(self.Take_Attendance)
        self.loadImageButtonTakeAttendance.setGeometry(QtCore.QRect(870, 100, 101, 21))
        self.loadImageButtonTakeAttendance.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 0, 0);")
        self.loadImageButtonTakeAttendance.setIcon(icon1)
        self.loadImageButtonTakeAttendance.setIconSize(QtCore.QSize(20, 20))
        self.loadImageButtonTakeAttendance.setObjectName("loadImageButtonTakeAttendance")
        self.LCDFaceCountTakeAttendance = QtWidgets.QLCDNumber(self.Take_Attendance)
        self.LCDFaceCountTakeAttendance.setGeometry(QtCore.QRect(780, 530, 121, 51))
        self.LCDFaceCountTakeAttendance.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.LCDFaceCountTakeAttendance.setFrameShape(QtWidgets.QFrame.Box)
        self.LCDFaceCountTakeAttendance.setObjectName("LCDFaceCountTakeAttendance")
        self.labelFaceCount2TakeAttendance = QtWidgets.QLabel(self.Take_Attendance)
        self.labelFaceCount2TakeAttendance.setGeometry(QtCore.QRect(780, 500, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelFaceCount2TakeAttendance.setFont(font)
        self.labelFaceCount2TakeAttendance.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.labelFaceCount2TakeAttendance.setTextFormat(QtCore.Qt.RichText)
        self.labelFaceCount2TakeAttendance.setScaledContents(True)
        self.labelFaceCount2TakeAttendance.setIndent(2)
        self.labelFaceCount2TakeAttendance.setObjectName("labelFaceCount2TakeAttendance")
        self.label_26 = QtWidgets.QLabel(self.Take_Attendance)
        self.label_26.setGeometry(QtCore.QRect(10, 610, 211, 51))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).jpg"))
        self.label_26.setObjectName("label_26")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photograph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tabs.addTab(self.Take_Attendance, icon2, "")
        self.Register_Faces = QtWidgets.QWidget()
        self.Register_Faces.setObjectName("Register_Faces")
        self.imageRecordingRegister_Faces = QtWidgets.QLabel(self.Register_Faces)
        self.imageRecordingRegister_Faces.setGeometry(QtCore.QRect(20, 10, 500, 500))
        self.imageRecordingRegister_Faces.setStyleSheet("image: url(.\\images/icons/facial-recognition.png);")
        self.imageRecordingRegister_Faces.setFrameShape(QtWidgets.QFrame.Box)
        self.imageRecordingRegister_Faces.setText("")
        self.imageRecordingRegister_Faces.setScaledContents(True)
        self.imageRecordingRegister_Faces.setAlignment(QtCore.Qt.AlignCenter)
        self.imageRecordingRegister_Faces.setObjectName("imageRecordingRegister_Faces")
        self.progressBar = QtWidgets.QProgressBar(self.Register_Faces)
        self.progressBar.setGeometry(QtCore.QRect(50, 520, 471, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 62)
        self.progressBar.setObjectName("progressBar")
        self.registerPushButtonRegister_Faces = QtWidgets.QPushButton(self.Register_Faces)
        self.registerPushButtonRegister_Faces.setGeometry(QtCore.QRect(670, 510, 285, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.registerPushButtonRegister_Faces.setFont(font)
        self.registerPushButtonRegister_Faces.setAutoFillBackground(False)
        self.registerPushButtonRegister_Faces.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.registerPushButtonRegister_Faces.setObjectName("registerPushButtonRegister_Faces")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Register_Faces)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 10, 421, 451))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.nAMELabel = QtWidgets.QLabel(self.groupBox_3)
        self.nAMELabel.setGeometry(QtCore.QRect(0, 70, 100, 20))
        font = QtGui.QFont()
        #-----------------------------------------------------------------------------------------------------------------------------
        font.setBold(True)
        font.setPointSize(9)
        #font.setWeight(75)
        self.nAMELabel.setFont(font)
        self.nAMELabel.setObjectName("nAMELabel")
        self.rOLL_NUMBERLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.rOLL_NUMBERLineEdit.setGeometry(QtCore.QRect(0, 160, 280, 20))
        self.rOLL_NUMBERLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rOLL_NUMBERLineEdit.setObjectName("rOLL_NUMBERLineEdit")
        self.nAMELineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.nAMELineEdit.setGeometry(QtCore.QRect(0, 90, 280, 20))
        self.nAMELineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nAMELineEdit.setObjectName("nAMELineEdit")
        self.sEMESTERComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sEMESTERComboBox.setGeometry(QtCore.QRect(0, 280, 280, 18))
        self.sEMESTERComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sEMESTERComboBox.setObjectName("sEMESTERComboBox")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sEMESTERComboBox.addItem("")
        self.sCHOOL_CODEComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sCHOOL_CODEComboBox.setGeometry(QtCore.QRect(0, 350, 280, 18))
        self.sCHOOL_CODEComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sCHOOL_CODEComboBox.setObjectName("sCHOOL_CODEComboBox")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sCHOOL_CODEComboBox.addItem("")
        self.sECTIONComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sECTIONComboBox.setGeometry(QtCore.QRect(0, 220, 280, 18))
        self.sECTIONComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sECTIONComboBox.setObjectName("sECTIONComboBox")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.sECTIONComboBox.addItem("")
        self.rOLL_NUMBERLabel = QtWidgets.QLabel(self.groupBox_3)
        self.rOLL_NUMBERLabel.setGeometry(QtCore.QRect(0, 140, 100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(9)
        self.rOLL_NUMBERLabel.setFont(font)
        self.rOLL_NUMBERLabel.setObjectName("rOLL_NUMBERLabel")
        self.sCHOOL_CODELabel = QtWidgets.QLabel(self.groupBox_3)
        self.sCHOOL_CODELabel.setGeometry(QtCore.QRect(0, 320, 100, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(9)
        self.sCHOOL_CODELabel.setFont(font)
        self.sCHOOL_CODELabel.setObjectName("sCHOOL_CODELabel")
        self.sEMESTERLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sEMESTERLabel.setGeometry(QtCore.QRect(0, 260, 100, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(9)
        self.sEMESTERLabel.setFont(font)
        self.sEMESTERLabel.setObjectName("sEMESTERLabel")
        self.sECTIONLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sECTIONLabel.setGeometry(QtCore.QRect(0, 200, 100, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setPointSize(9)
        self.sECTIONLabel.setFont(font)
        self.sECTIONLabel.setObjectName("sECTIONLabel")
        self.label_30 = QtWidgets.QLabel(self.Register_Faces)
        self.label_30.setGeometry(QtCore.QRect(0, 610, 211, 51))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(".\\Webp.net-resizeimage (1).jpg"))
        self.label_30.setObjectName("label_30")
        self.Tabs.addTab(self.Register_Faces, icon, "")
        self.RESULTS = QtWidgets.QWidget()
        self.RESULTS.setObjectName("RESULTS")
        self.tableResultsResult = QtWidgets.QTableWidget(self.RESULTS)
        self.tableResultsResult.setGeometry(QtCore.QRect(30, 60, 341, 511))
        self.tableResultsResult.setStyleSheet("gridline-color: rgb(0, 255, 0);\n"
"selection-background-color: rgb(0, 216, 104);")
        self.tableResultsResult.setAlternatingRowColors(True)
        self.tableResultsResult.setObjectName("tableResultsResult")
        self.tableResultsResult.setColumnCount(3)
        self.tableResultsResult.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableResultsResult.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResultsResult.setItem(3, 0, item)
        self.labelResultResults = QtWidgets.QLabel(self.RESULTS)
        self.labelResultResults.setGeometry(QtCore.QRect(150, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelResultResults.setFont(font)
        self.labelResultResults.setObjectName("labelResultResults")
        self.groupBox_4 = QtWidgets.QGroupBox(self.RESULTS)
        self.groupBox_4.setGeometry(QtCore.QRect(400, 100, 331, 401))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableAbsentsResult = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableAbsentsResult.setGeometry(QtCore.QRect(40, 50, 251, 321))
        self.tableAbsentsResult.setStyleSheet("gridline-color: rgb(0, 255, 0);\n"
"selection-background-color: rgb(0, 216, 104);")
        self.tableAbsentsResult.setObjectName("tableAbsentsResult")
        self.tableAbsentsResult.setColumnCount(2)
        self.tableAbsentsResult.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableAbsentsResult.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbsentsResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbsentsResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbsentsResult.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbsentsResult.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("kundan.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.tableAbsentsResult.setItem(1, 0, item)
        self.labelTotalPresentsResults = QtWidgets.QLabel(self.RESULTS)
        self.labelTotalPresentsResults.setGeometry(QtCore.QRect(770, 140, 91, 16))
        self.labelTotalPresentsResults.setObjectName("labelTotalPresentsResults")
        self.lcdCounterTotalPresentsResults = QtWidgets.QLCDNumber(self.RESULTS)
        self.lcdCounterTotalPresentsResults.setGeometry(QtCore.QRect(770, 170, 121, 61))
        self.lcdCounterTotalPresentsResults.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounterTotalPresentsResults.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounterTotalPresentsResults.setObjectName("lcdCounterTotalPresentsResults")
        self.labelTotalAbsentsResults = QtWidgets.QLabel(self.RESULTS)
        self.labelTotalAbsentsResults.setGeometry(QtCore.QRect(900, 140, 91, 16))
        self.labelTotalAbsentsResults.setObjectName("labelTotalAbsentsResults")
        self.lcdCounterTotalAbsentsResults = QtWidgets.QLCDNumber(self.RESULTS)
        self.lcdCounterTotalAbsentsResults.setGeometry(QtCore.QRect(900, 170, 121, 61))
        self.lcdCounterTotalAbsentsResults.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounterTotalAbsentsResults.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounterTotalAbsentsResults.setObjectName("lcdCounterTotalAbsentsResults")
        self.pushButtonConfirmAndUpdate = QtWidgets.QPushButton(self.RESULTS)
        self.pushButtonConfirmAndUpdate.setGeometry(QtCore.QRect(800, 260, 201, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonConfirmAndUpdate.setFont(font)
        self.pushButtonConfirmAndUpdate.setObjectName("pushButtonConfirmAndUpdate")
        self.EditButtonResults = QtWidgets.QPushButton(self.RESULTS)
        self.EditButtonResults.setGeometry(QtCore.QRect(850, 20, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.EditButtonResults.setFont(font)
        self.EditButtonResults.setStyleSheet("alternate-background-color: rgb(255, 255, 0);\n"
"selection-color: rgb(0, 255, 255);\n"
"selection-background-color: rgb(255, 170, 0);")
        self.EditButtonResults.setObjectName("EditButtonResults")
        self.labelPresidencyLogo = QtWidgets.QLabel(self.RESULTS)
        self.labelPresidencyLogo.setGeometry(QtCore.QRect(0, 610, 211, 51))
        self.labelPresidencyLogo.setText("")
        self.labelPresidencyLogo.setPixmap(QtGui.QPixmap("Webp.net-resizeimage (1).jpg"))
        self.labelPresidencyLogo.setObjectName("labelPresidencyLogo")
        self.groupBox_4.raise_()
        self.tableResultsResult.raise_()
        self.labelResultResults.raise_()
        self.labelTotalPresentsResults.raise_()
        self.lcdCounterTotalPresentsResults.raise_()
        self.labelTotalAbsentsResults.raise_()
        self.lcdCounterTotalAbsentsResults.raise_()
        self.pushButtonConfirmAndUpdate.raise_()
        self.EditButtonResults.raise_()
        self.labelPresidencyLogo.raise_()
        self.Tabs.addTab(self.RESULTS, "")
        self.M_Attendance = QtWidgets.QWidget()
        self.M_Attendance.setObjectName("M_Attendance")
        self.ManualAttendanceTable = QtWidgets.QTableWidget(self.M_Attendance)
        self.ManualAttendanceTable.setGeometry(QtCore.QRect(30, 20, 331, 641))
        self.ManualAttendanceTable.setDragEnabled(True)
        self.ManualAttendanceTable.setAlternatingRowColors(True)
        self.ManualAttendanceTable.setObjectName("ManualAttendanceTable")
        self.ManualAttendanceTable.setColumnCount(3)
        self.ManualAttendanceTable.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ManualAttendanceTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.ManualAttendanceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ManualAttendanceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ManualAttendanceTable.setHorizontalHeaderItem(2, item)
        self.ChooseClassDetails = QtWidgets.QGroupBox(self.M_Attendance)
        self.ChooseClassDetails.setGeometry(QtCore.QRect(460, 20, 541, 321))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ChooseClassDetails.setFont(font)
        self.ChooseClassDetails.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ChooseClassDetails.setAutoFillBackground(False)
        self.ChooseClassDetails.setStyleSheet("background-color: rgb(123, 123, 185);")
        self.ChooseClassDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.ChooseClassDetails.setFlat(False)
        self.ChooseClassDetails.setCheckable(False)
        self.ChooseClassDetails.setObjectName("ChooseClassDetails")
        self.labelClassChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelClassChooseDetails.setGeometry(QtCore.QRect(10, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelClassChooseDetails.setFont(font)
        self.labelClassChooseDetails.setObjectName("labelClassChooseDetails")
        self.labelFacultyNameChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelFacultyNameChooseDetails.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFacultyNameChooseDetails.setFont(font)
        self.labelFacultyNameChooseDetails.setObjectName("labelFacultyNameChooseDetails")
        self.labelCourseCodeChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelCourseCodeChooseDetails.setGeometry(QtCore.QRect(10, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCourseCodeChooseDetails.setFont(font)
        self.labelCourseCodeChooseDetails.setObjectName("labelCourseCodeChooseDetails")
        self.labelPeriodNumberChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelPeriodNumberChooseDetails.setGeometry(QtCore.QRect(10, 240, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPeriodNumberChooseDetails.setFont(font)
        self.labelPeriodNumberChooseDetails.setObjectName("labelPeriodNumberChooseDetails")
        self.lineEditFacultyName = QtWidgets.QLineEdit(self.ChooseClassDetails)
        self.lineEditFacultyName.setGeometry(QtCore.QRect(10, 130, 191, 20))
        self.lineEditFacultyName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditFacultyName.setObjectName("lineEditFacultyName")
        self.spinBoxPeriodNoChooseDetails = QtWidgets.QSpinBox(self.ChooseClassDetails)
        self.spinBoxPeriodNoChooseDetails.setGeometry(QtCore.QRect(10, 260, 42, 22))
        self.spinBoxPeriodNoChooseDetails.setObjectName("spinBoxPeriodNoChooseDetails")
        self.comboBoxSectionCode = QtWidgets.QComboBox(self.ChooseClassDetails)
        self.comboBoxSectionCode.setGeometry(QtCore.QRect(10, 60, 191, 22))
        self.comboBoxSectionCode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxSectionCode.setObjectName("comboBoxSectionCode")
        self.comboBoxSectionCode.addItem("")
        self.comboBoxSectionCode.addItem("")
        self.comboBoxSectionCode.addItem("")
        self.comboBoxSectionCode.addItem("")
        self.comboBoxSectionCode.addItem("")
        self.comboBoxCourseCode = QtWidgets.QComboBox(self.ChooseClassDetails)
        self.comboBoxCourseCode.setGeometry(QtCore.QRect(10, 190, 191, 22))
        self.comboBoxCourseCode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxCourseCode.setObjectName("comboBoxCourseCode")
        self.comboBoxCourseCode.addItem("")
        self.comboBoxCourseCode.addItem("")
        self.comboBoxCourseCode.addItem("")
        self.comboBoxCourseCode.addItem("")
        self.comboBoxCourseCode.addItem("")
        self.labelSemesterChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelSemesterChooseDetails.setGeometry(QtCore.QRect(310, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSemesterChooseDetails.setFont(font)
        self.labelSemesterChooseDetails.setObjectName("labelSemesterChooseDetails")
        self.comboBoxSemester = QtWidgets.QComboBox(self.ChooseClassDetails)
        self.comboBoxSemester.setGeometry(QtCore.QRect(310, 190, 191, 22))
        self.comboBoxSemester.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxSemester.setObjectName("comboBoxSemester")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.comboBoxSemester.addItem("")
        self.labelSchoolChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelSchoolChooseDetails.setGeometry(QtCore.QRect(310, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSchoolChooseDetails.setFont(font)
        self.labelSchoolChooseDetails.setObjectName("labelSchoolChooseDetails")
        self.labelBranchChooseDetails = QtWidgets.QLabel(self.ChooseClassDetails)
        self.labelBranchChooseDetails.setGeometry(QtCore.QRect(310, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelBranchChooseDetails.setFont(font)
        self.labelBranchChooseDetails.setObjectName("labelBranchChooseDetails")
        self.comboBoxSchoolCode = QtWidgets.QComboBox(self.ChooseClassDetails)
        self.comboBoxSchoolCode.setGeometry(QtCore.QRect(310, 60, 191, 22))
        self.comboBoxSchoolCode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxSchoolCode.setObjectName("comboBoxSchoolCode")
        self.comboBoxSchoolCode.addItem("")
        self.comboBoxSchoolCode.addItem("")
        self.comboBoxSchoolCode.addItem("")
        self.comboBoxSchoolCode.addItem("")
        self.comboBoxSchoolCode.addItem("")
        self.comboBoxSchoolCode.addItem("")
        self.comboBoxBranchDetails = QtWidgets.QComboBox(self.ChooseClassDetails)
        self.comboBoxBranchDetails.setGeometry(QtCore.QRect(310, 130, 191, 22))
        self.comboBoxBranchDetails.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxBranchDetails.setObjectName("comboBoxBranchDetails")
        self.comboBoxBranchDetails.addItem("")
        self.comboBoxBranchDetails.addItem("")
        self.comboBoxBranchDetails.addItem("")
        self.comboBoxBranchDetails.addItem("")
        self.comboBoxBranchDetails.addItem("")
        self.comboBoxBranchDetails.addItem("")
        self.comboBoxBranchDetails.addItem("")
        self.pushButtonOKChooseDetails = QtWidgets.QPushButton(self.ChooseClassDetails)
        self.pushButtonOKChooseDetails.setGeometry(QtCore.QRect(180, 290, 161, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOKChooseDetails.setFont(font)
        self.pushButtonOKChooseDetails.setObjectName("pushButtonOKChooseDetails")
        self.groupBoxResultM_Attendace = QtWidgets.QGroupBox(self.M_Attendance)
        self.groupBoxResultM_Attendace.setGeometry(QtCore.QRect(470, 370, 521, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBoxResultM_Attendace.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBoxResultM_Attendace.setFont(font)
        self.groupBoxResultM_Attendace.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);")
        self.groupBoxResultM_Attendace.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxResultM_Attendace.setObjectName("groupBoxResultM_Attendace")
        self.lcdCounterTotalAbsentM_Attendance = QtWidgets.QLCDNumber(self.groupBoxResultM_Attendace)
        self.lcdCounterTotalAbsentM_Attendance.setGeometry(QtCore.QRect(350, 90, 121, 61))
        self.lcdCounterTotalAbsentM_Attendance.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounterTotalAbsentM_Attendance.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounterTotalAbsentM_Attendance.setObjectName("lcdCounterTotalAbsentM_Attendance")
        self.labelTotalAbsentM_Attendance = QtWidgets.QLabel(self.groupBoxResultM_Attendace)
        self.labelTotalAbsentM_Attendance.setGeometry(QtCore.QRect(350, 60, 91, 16))
        self.labelTotalAbsentM_Attendance.setObjectName("labelTotalAbsentM_Attendance")
        self.lcdCounterTotalPresentM_Attendance = QtWidgets.QLCDNumber(self.groupBoxResultM_Attendace)
        self.lcdCounterTotalPresentM_Attendance.setGeometry(QtCore.QRect(200, 90, 121, 61))
        self.lcdCounterTotalPresentM_Attendance.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"")
        self.lcdCounterTotalPresentM_Attendance.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdCounterTotalPresentM_Attendance.setObjectName("lcdCounterTotalPresentM_Attendance")
        self.labelTotalPresentM_Attendance = QtWidgets.QLabel(self.groupBoxResultM_Attendace)
        self.labelTotalPresentM_Attendance.setGeometry(QtCore.QRect(200, 60, 91, 16))
        self.labelTotalPresentM_Attendance.setObjectName("labelTotalPresentM_Attendance")
        self.pushButtonResetResultM_Attendance = QtWidgets.QPushButton(self.groupBoxResultM_Attendace)
        self.pushButtonResetResultM_Attendance.setGeometry(QtCore.QRect(90, 90, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonResetResultM_Attendance.setFont(font)
        self.pushButtonResetResultM_Attendance.setObjectName("pushButtonResetResultM_Attendance")
        self.pushButtonSaveResultM_Attendance = QtWidgets.QPushButton(self.groupBoxResultM_Attendace)
        self.pushButtonSaveResultM_Attendance.setGeometry(QtCore.QRect(90, 130, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSaveResultM_Attendance.setFont(font)
        self.pushButtonSaveResultM_Attendance.setObjectName("pushButtonSaveResultM_Attendance")
        self.pushButtonConfirmAndUpdateM_Attendance = QtWidgets.QPushButton(self.groupBoxResultM_Attendace)
        self.pushButtonConfirmAndUpdateM_Attendance.setGeometry(QtCore.QRect(150, 210, 311, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonConfirmAndUpdateM_Attendance.setFont(font)
        self.pushButtonConfirmAndUpdateM_Attendance.setObjectName("pushButtonConfirmAndUpdateM_Attendance")
        self.Tabs.addTab(self.M_Attendance, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.groupBoxSettings = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBoxSettings.setGeometry(QtCore.QRect(10, 70, 1011, 421))
        self.groupBoxSettings.setTitle("")
        self.groupBoxSettings.setObjectName("groupBoxSettings")
        self.iMAGE_PATHLineEdit = QtWidgets.QLineEdit(self.groupBoxSettings)
        self.iMAGE_PATHLineEdit.setGeometry(QtCore.QRect(190, 90, 565, 20))
        self.iMAGE_PATHLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.iMAGE_PATHLineEdit.setObjectName("iMAGE_PATHLineEdit")
        self.dATASET_SAVE_PATHLineEdit = QtWidgets.QLineEdit(self.groupBoxSettings)
        self.dATASET_SAVE_PATHLineEdit.setGeometry(QtCore.QRect(190, 20, 565, 20))
        self.dATASET_SAVE_PATHLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dATASET_SAVE_PATHLineEdit.setObjectName("dATASET_SAVE_PATHLineEdit")
        self.eXCEL_SHEET_PATHLabel = QtWidgets.QLabel(self.groupBoxSettings)
        self.eXCEL_SHEET_PATHLabel.setGeometry(QtCore.QRect(190, 140, 99, 20))
        self.eXCEL_SHEET_PATHLabel.setObjectName("eXCEL_SHEET_PATHLabel")
        self.saveButtonSettings = QtWidgets.QPushButton(self.groupBoxSettings)
        self.saveButtonSettings.setGeometry(QtCore.QRect(180, 240, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.saveButtonSettings.setFont(font)
        self.saveButtonSettings.setAutoFillBackground(False)
        self.saveButtonSettings.setStyleSheet("color: red;\n"
"background-color: rgba(170, 255, 255, 150);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.saveButtonSettings.setObjectName("saveButtonSettings")
        self.eXCEL_SHEET_PATHLineEdit = QtWidgets.QLineEdit(self.groupBoxSettings)
        self.eXCEL_SHEET_PATHLineEdit.setGeometry(QtCore.QRect(190, 160, 565, 20))
        self.eXCEL_SHEET_PATHLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.eXCEL_SHEET_PATHLineEdit.setObjectName("eXCEL_SHEET_PATHLineEdit")
        self.iMAGE_PATHLabel = QtWidgets.QLabel(self.groupBoxSettings)
        self.iMAGE_PATHLabel.setGeometry(QtCore.QRect(190, 70, 64, 20))
        self.iMAGE_PATHLabel.setObjectName("iMAGE_PATHLabel")
        self.dATASET_SAVE_PATHLabel = QtWidgets.QLabel(self.groupBoxSettings)
        self.dATASET_SAVE_PATHLabel.setGeometry(QtCore.QRect(190, 0, 108, 20))
        self.dATASET_SAVE_PATHLabel.setObjectName("dATASET_SAVE_PATHLabel")
        self.labelPresidencyLogoSettings = QtWidgets.QLabel(self.tabSettings)
        self.labelPresidencyLogoSettings.setGeometry(QtCore.QRect(0, 610, 211, 51))
        self.labelPresidencyLogoSettings.setText("")
        self.labelPresidencyLogoSettings.setPixmap(QtGui.QPixmap("Webp.net-resizeimage (1).jpg"))
        self.labelPresidencyLogoSettings.setObjectName("labelPresidencyLogoSettings")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tabs.addTab(self.tabSettings, icon4, "")
        self.tabAboutUs = QtWidgets.QWidget()
        self.tabAboutUs.setObjectName("tabAboutUs")
        self.textBrowserAboutUs = QtWidgets.QTextBrowser(self.tabAboutUs)
        self.textBrowserAboutUs.setGeometry(QtCore.QRect(-10, 30, 1031, 651))
        self.textBrowserAboutUs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowserAboutUs.setObjectName("textBrowserAboutUs")
        self.labelBrainsBehindTheProject = QtWidgets.QLabel(self.tabAboutUs)
        self.labelBrainsBehindTheProject.setGeometry(QtCore.QRect(10, 260, 981, 51))
        self.labelBrainsBehindTheProject.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.labelBrainsBehindTheProject.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBrainsBehindTheProject.setObjectName("labelBrainsBehindTheProject")
        self.labelKundanPhoto = QtWidgets.QLabel(self.tabAboutUs)
        self.labelKundanPhoto.setGeometry(QtCore.QRect(50, 330, 191, 191))
        self.labelKundanPhoto.setStyleSheet("image: url(:/photos/kundan.jpeg);")
        self.labelKundanPhoto.setText("")
        self.labelKundanPhoto.setPixmap(QtGui.QPixmap("Webp.net-resizeimage (1).png"))
        self.labelKundanPhoto.setObjectName("labelKundanPhoto")
        self.labelCastroPhoto = QtWidgets.QLabel(self.tabAboutUs)
        self.labelCastroPhoto.setGeometry(QtCore.QRect(300, 330, 211, 191))
        self.labelCastroPhoto.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/photos/castro.png);")
        self.labelCastroPhoto.setText("")
        self.labelCastroPhoto.setPixmap(QtGui.QPixmap("Webp.net-resizeimage (3).png"))
        self.labelCastroPhoto.setObjectName("labelCastroPhoto")
        self.labelAzraPhoto = QtWidgets.QLabel(self.tabAboutUs)
        self.labelAzraPhoto.setGeometry(QtCore.QRect(550, 320, 181, 211))
        self.labelAzraPhoto.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/photos/azra.jpeg);")
        self.labelAzraPhoto.setText("")
        self.labelAzraPhoto.setPixmap(QtGui.QPixmap("Webp.net-resizeimage (2).png"))
        self.labelAzraPhoto.setObjectName("labelAzraPhoto")
        self.labelPrudhviGuide = QtWidgets.QLabel(self.tabAboutUs)
        self.labelPrudhviGuide.setGeometry(QtCore.QRect(760, 300, 221, 241))
        self.labelPrudhviGuide.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/photos/prudhvi.png);")
        self.labelPrudhviGuide.setText("")
        self.labelPrudhviGuide.setPixmap(QtGui.QPixmap("Webp.net-resizeimage (4).png"))
        self.labelPrudhviGuide.setObjectName("labelPrudhviGuide")
        self.labelNameKundan = QtWidgets.QLabel(self.tabAboutUs)
        self.labelNameKundan.setGeometry(QtCore.QRect(16, 542, 221, 81))
        self.labelNameKundan.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelNameKundan.setObjectName("labelNameKundan")
        self.labelNameCastro = QtWidgets.QLabel(self.tabAboutUs)
        self.labelNameCastro.setGeometry(QtCore.QRect(300, 540, 221, 81))
        self.labelNameCastro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelNameCastro.setObjectName("labelNameCastro")
        self.labelNameAzra = QtWidgets.QLabel(self.tabAboutUs)
        self.labelNameAzra.setGeometry(QtCore.QRect(540, 540, 221, 81))
        self.labelNameAzra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelNameAzra.setObjectName("labelNameAzra")
        self.labelNamePrudhvi = QtWidgets.QLabel(self.tabAboutUs)
        self.labelNamePrudhvi.setGeometry(QtCore.QRect(780, 540, 221, 81))
        self.labelNamePrudhvi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelNamePrudhvi.setObjectName("labelNamePrudhvi")
        self.labelOurGuide = QtWidgets.QLabel(self.tabAboutUs)
        self.labelOurGuide.setGeometry(QtCore.QRect(400, 120, 201, 101))
        self.labelOurGuide.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelOurGuide.setObjectName("labelOurGuide")
        self.textBrowserAboutUs.raise_()
        self.labelBrainsBehindTheProject.raise_()
        self.labelCastroPhoto.raise_()
        self.labelKundanPhoto.raise_()
        self.labelAzraPhoto.raise_()
        self.labelPrudhviGuide.raise_()
        self.labelNameKundan.raise_()
        self.labelNameCastro.raise_()
        self.labelNameAzra.raise_()
        self.labelNamePrudhvi.raise_()
        self.labelOurGuide.raise_()
        self.Tabs.addTab(self.tabAboutUs, "")
        self.gridLayout.addWidget(self.Tabs, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionoen = QtWidgets.QAction(MainWindow)
        self.actionoen.setObjectName("actionoen")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionuct = QtWidgets.QAction(MainWindow)
        self.actionuct.setObjectName("actionuct")
        self.actioncoopy = QtWidgets.QAction(MainWindow)
        self.actioncoopy.setObjectName("actioncoopy")
        self.actionTAKE_ATTENDANCE = QtWidgets.QAction(MainWindow)
        self.actionTAKE_ATTENDANCE.setIcon(icon1)
        self.actionTAKE_ATTENDANCE.setObjectName("actionTAKE_ATTENDANCE")
        self.actionREGISTER = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionREGISTER.setIcon(icon5)
        self.actionREGISTER.setObjectName("actionREGISTER")
        self.actionSETTINGS = QtWidgets.QAction(MainWindow)
        self.actionSETTINGS.setIcon(icon4)
        self.actionSETTINGS.setObjectName("actionSETTINGS")

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UNIVERSITY_PROJECT-1"))
        self.labelFaceCountTakeAttendance.setText(_translate("MainWindow", "Total Face Count"))
        self.startProcessingButton.setText(_translate("MainWindow", "Start Processing"))
        self.startProcessingButton.setShortcut(_translate("MainWindow", "F5"))
        self.PROCESSING_STATUS.setText(_translate("MainWindow", "PROCESSING_STATUS :"))
        self.imagePath.setText(_translate("MainWindow", "imagePathTakeAttendance"))
        self.loadImageButtonTakeAttendance.setText(_translate("MainWindow", "Load Image"))
        self.loadImageButtonTakeAttendance.setShortcut(_translate("MainWindow", "F5"))
        self.labelFaceCount2TakeAttendance.setText(_translate("MainWindow", "identified Face Count"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Take_Attendance), _translate("MainWindow", "Take_Attendance"))
        self.registerPushButtonRegister_Faces.setText(_translate("MainWindow", "REGISTER"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fill the details Below"))
        self.nAMELabel.setText(_translate("MainWindow", "NAME"))
        self.sEMESTERComboBox.setItemText(0, _translate("MainWindow", "SEM_1"))
        self.sEMESTERComboBox.setItemText(1, _translate("MainWindow", "SEM_2"))
        self.sEMESTERComboBox.setItemText(2, _translate("MainWindow", "SEM_3"))
        self.sEMESTERComboBox.setItemText(3, _translate("MainWindow", "SEM_4"))
        self.sEMESTERComboBox.setItemText(4, _translate("MainWindow", "SEM_5"))
        self.sEMESTERComboBox.setItemText(5, _translate("MainWindow", "SEM_6"))
        self.sEMESTERComboBox.setItemText(6, _translate("MainWindow", "SEM_7"))
        self.sEMESTERComboBox.setItemText(7, _translate("MainWindow", "SEM_8"))
        self.sEMESTERComboBox.setItemText(8, _translate("MainWindow", "SEM_9"))
        self.sEMESTERComboBox.setItemText(9, _translate("MainWindow", "SEM_10"))
        self.sCHOOL_CODEComboBox.setItemText(0, _translate("MainWindow", "SOE"))
        self.sCHOOL_CODEComboBox.setItemText(1, _translate("MainWindow", "SOM"))
        self.sCHOOL_CODEComboBox.setItemText(2, _translate("MainWindow", "SOC"))
        self.sCHOOL_CODEComboBox.setItemText(3, _translate("MainWindow", "SOL"))
        self.sCHOOL_CODEComboBox.setItemText(4, _translate("MainWindow", "M.TECH"))
        self.sCHOOL_CODEComboBox.setItemText(5, _translate("MainWindow", "Phd"))
        self.sECTIONComboBox.setItemText(0, _translate("MainWindow", "5cse5"))
        self.sECTIONComboBox.setItemText(1, _translate("MainWindow", "5cse6"))
        self.sECTIONComboBox.setItemText(2, _translate("MainWindow", "5cse7"))
        self.sECTIONComboBox.setItemText(3, _translate("MainWindow", "5cse8"))
        self.sECTIONComboBox.setItemText(4, _translate("MainWindow", "5cse9"))
        self.sECTIONComboBox.setItemText(5, _translate("MainWindow", "5cse10"))
        self.rOLL_NUMBERLabel.setText(_translate("MainWindow", "ID_NUMBER"))
        self.sCHOOL_CODELabel.setText(_translate("MainWindow", "SCHOOL"))
        self.sEMESTERLabel.setText(_translate("MainWindow", "SEMESTER"))
        self.sECTIONLabel.setText(_translate("MainWindow", "SECTION"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Register_Faces), _translate("MainWindow", "Register_Faces"))
        item = self.tableResultsResult.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableResultsResult.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableResultsResult.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableResultsResult.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableResultsResult.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableResultsResult.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableResultsResult.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableResultsResult.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableResultsResult.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableResultsResult.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableResultsResult.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableResultsResult.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableResultsResult.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableResultsResult.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableResultsResult.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableResultsResult.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableResultsResult.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableResultsResult.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableResultsResult.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableResultsResult.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableResultsResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID.No"))
        item = self.tableResultsResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableResultsResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        __sortingEnabled = self.tableResultsResult.isSortingEnabled()
        self.tableResultsResult.setSortingEnabled(False)
        item = self.tableResultsResult.item(1, 0)
        item.setText(_translate("MainWindow", "20171CSE0331"))
        item = self.tableResultsResult.item(1, 1)
        item.setText(_translate("MainWindow", "KUNDAN "))
        item = self.tableResultsResult.item(1, 2)
        item.setText(_translate("MainWindow", "P"))
        item = self.tableResultsResult.item(2, 0)
        item.setText(_translate("MainWindow", "20171BSC0222"))
        item = self.tableResultsResult.item(2, 1)
        item.setText(_translate("MainWindow", "PURNESH"))
        item = self.tableResultsResult.item(2, 2)
        item.setText(_translate("MainWindow", "P"))
        self.tableResultsResult.setSortingEnabled(__sortingEnabled)
        self.labelResultResults.setText(_translate("MainWindow", "Result"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Absents"))
        item = self.tableAbsentsResult.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableAbsentsResult.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableAbsentsResult.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableAbsentsResult.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableAbsentsResult.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableAbsentsResult.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableAbsentsResult.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableAbsentsResult.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableAbsentsResult.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableAbsentsResult.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableAbsentsResult.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableAbsentsResult.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableAbsentsResult.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableAbsentsResult.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableAbsentsResult.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableAbsentsResult.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableAbsentsResult.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableAbsentsResult.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableAbsentsResult.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableAbsentsResult.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableAbsentsResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID.No"))
        item = self.tableAbsentsResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        __sortingEnabled = self.tableAbsentsResult.isSortingEnabled()
        self.tableAbsentsResult.setSortingEnabled(False)
        item = self.tableAbsentsResult.item(0, 0)
        item.setText(_translate("MainWindow", "2017101SSSS"))
        item = self.tableAbsentsResult.item(0, 1)
        item.setText(_translate("MainWindow", "SIDHARTH"))
        self.tableAbsentsResult.setSortingEnabled(__sortingEnabled)
        self.labelTotalPresentsResults.setText(_translate("MainWindow", "Total Presents"))
        self.labelTotalAbsentsResults.setText(_translate("MainWindow", "Total Absents"))
        self.pushButtonConfirmAndUpdate.setText(_translate("MainWindow", "CONFIRM And Update in ERP"))
        self.EditButtonResults.setText(_translate("MainWindow", "EDIT"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.RESULTS), _translate("MainWindow", "RESULTS"))
        item = self.ManualAttendanceTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.ManualAttendanceTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.ManualAttendanceTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.ManualAttendanceTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.ManualAttendanceTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.ManualAttendanceTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.ManualAttendanceTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.ManualAttendanceTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.ManualAttendanceTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.ManualAttendanceTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.ManualAttendanceTable.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.ManualAttendanceTable.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.ManualAttendanceTable.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.ManualAttendanceTable.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.ManualAttendanceTable.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.ManualAttendanceTable.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.ManualAttendanceTable.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.ManualAttendanceTable.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "19"))
        item = self.ManualAttendanceTable.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "18"))
        item = self.ManualAttendanceTable.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.ManualAttendanceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID.No"))
        item = self.ManualAttendanceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.ManualAttendanceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Attendance(X/A)"))
        self.ChooseClassDetails.setTitle(_translate("MainWindow", "Choose Class Details"))
        self.labelClassChooseDetails.setText(_translate("MainWindow", "Class."))
        self.labelFacultyNameChooseDetails.setText(_translate("MainWindow", "Faculty Name."))
        self.labelCourseCodeChooseDetails.setText(_translate("MainWindow", "Course Code."))
        self.labelPeriodNumberChooseDetails.setText(_translate("MainWindow", "Period No."))
        self.comboBoxSectionCode.setItemText(0, _translate("MainWindow", "5CSE1"))
        self.comboBoxSectionCode.setItemText(1, _translate("MainWindow", "5CSE2"))
        self.comboBoxSectionCode.setItemText(2, _translate("MainWindow", "5CSE3"))
        self.comboBoxSectionCode.setItemText(3, _translate("MainWindow", "5CSE4"))
        self.comboBoxSectionCode.setItemText(4, _translate("MainWindow", "5CSE5"))
        self.comboBoxCourseCode.setItemText(0, _translate("MainWindow", "CSE123"))
        self.comboBoxCourseCode.setItemText(1, _translate("MainWindow", "CSE001"))
        self.comboBoxCourseCode.setItemText(2, _translate("MainWindow", "CSE258"))
        self.comboBoxCourseCode.setItemText(3, _translate("MainWindow", "CSE985"))
        self.comboBoxCourseCode.setItemText(4, _translate("MainWindow", "CSE456"))
        self.labelSemesterChooseDetails.setText(_translate("MainWindow", "Semester."))
        self.comboBoxSemester.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxSemester.setItemText(1, _translate("MainWindow", "2"))
        self.comboBoxSemester.setItemText(2, _translate("MainWindow", "3"))
        self.comboBoxSemester.setItemText(3, _translate("MainWindow", "4"))
        self.comboBoxSemester.setItemText(4, _translate("MainWindow", "5"))
        self.comboBoxSemester.setItemText(5, _translate("MainWindow", "6"))
        self.comboBoxSemester.setItemText(6, _translate("MainWindow", "7"))
        self.comboBoxSemester.setItemText(7, _translate("MainWindow", "8"))
        self.labelSchoolChooseDetails.setText(_translate("MainWindow", "School."))
        self.labelBranchChooseDetails.setText(_translate("MainWindow", "Branch."))
        self.comboBoxSchoolCode.setItemText(0, _translate("MainWindow", "SOE"))
        self.comboBoxSchoolCode.setItemText(1, _translate("MainWindow", "SOM"))
        self.comboBoxSchoolCode.setItemText(2, _translate("MainWindow", "SOL"))
        self.comboBoxSchoolCode.setItemText(3, _translate("MainWindow", "SOC"))
        self.comboBoxSchoolCode.setItemText(4, _translate("MainWindow", "M.TECH"))
        self.comboBoxSchoolCode.setItemText(5, _translate("MainWindow", "P.hD"))
        self.comboBoxBranchDetails.setItemText(0, _translate("MainWindow", "CSE"))
        self.comboBoxBranchDetails.setItemText(1, _translate("MainWindow", "EEE"))
        self.comboBoxBranchDetails.setItemText(2, _translate("MainWindow", "ECE"))
        self.comboBoxBranchDetails.setItemText(3, _translate("MainWindow", "MEC"))
        self.comboBoxBranchDetails.setItemText(4, _translate("MainWindow", "PET"))
        self.comboBoxBranchDetails.setItemText(5, _translate("MainWindow", "BBA"))
        self.comboBoxBranchDetails.setItemText(6, _translate("MainWindow", "BA"))
        self.pushButtonOKChooseDetails.setText(_translate("MainWindow", "OK"))
        self.groupBoxResultM_Attendace.setTitle(_translate("MainWindow", "Result"))
        self.labelTotalAbsentM_Attendance.setText(_translate("MainWindow", "Total Absents"))
        self.labelTotalPresentM_Attendance.setText(_translate("MainWindow", "Total Presents"))
        self.pushButtonResetResultM_Attendance.setText(_translate("MainWindow", "Reset"))
        self.pushButtonSaveResultM_Attendance.setText(_translate("MainWindow", "Save "))
        self.pushButtonConfirmAndUpdateM_Attendance.setText(_translate("MainWindow", "Confirm And Update in ERP"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.M_Attendance), _translate("MainWindow", "M_Attendance"))
        self.eXCEL_SHEET_PATHLabel.setText(_translate("MainWindow", "EXCEL_SHEET_PATH"))
        self.saveButtonSettings.setText(_translate("MainWindow", "SAVE BUTTON"))
        self.iMAGE_PATHLabel.setText(_translate("MainWindow", "IMAGE_PATH"))
        self.dATASET_SAVE_PATHLabel.setText(_translate("MainWindow", "DATASET_SAVE_PATH"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabSettings), _translate("MainWindow", "SETTINGS"))
        self.textBrowserAboutUs.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\"> This facial Recognition Attendence System is a part of University Project held in Pesidency University Computer Science Branch for       the year 2019-20.</span></p></body></html>"))
        self.labelBrainsBehindTheProject.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Brains Behind The Project</span></p></body></html>"))
        self.labelNameKundan.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">KUNDAN MUNDA NS </span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0331</span></p></body></html>"))
        self.labelNameCastro.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">CASTRO K JOSEPH </span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0145</span></p></body></html>"))
        self.labelNameAzra.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">AZRA BANU </span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0105</span></p></body></html>"))
        self.labelNamePrudhvi.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">PRUDHVI RAJ</span></p><p><span style=\" font-size:16pt; font-weight:600;\">20171CSE0138</span></p></body></html>"))
        self.labelOurGuide.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Our Guide</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">MS.ILLA CHANDRAKAR</span></p></body></html>"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabAboutUs), _translate("MainWindow", "About Us"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionoen.setText(_translate("MainWindow", "open"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))
        self.actionuct.setText(_translate("MainWindow", "uct"))
        self.actioncoopy.setText(_translate("MainWindow", "coopy"))
        self.actionTAKE_ATTENDANCE.setText(_translate("MainWindow", "TAKE_ATTENDANCE"))
        self.actionTAKE_ATTENDANCE.setToolTip(_translate("MainWindow", "takes_attendance"))
        self.actionREGISTER.setText(_translate("MainWindow", "REGISTER"))
        self.actionREGISTER.setToolTip(_translate("MainWindow", "maps to register screen"))
        self.actionSETTINGS.setText(_translate("MainWindow", "SETTINGS"))
        self.actionSETTINGS.setToolTip(_translate("MainWindow", "configuring the locations"))
#import iconsPackage_rc
#import iconsQT_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
